codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 60%
        threshold: 10%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "setup_verify.py"
  - "examples.py"
  - "stats.py"
  - "check_setup.py"
  - "**/__pycache__"
  - "venv/"
  - ".venv/"
